# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: firebase_snippets_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  cloud_firestore: ^4.8.5
  cloud_firestore_odm: ^1.0.0-dev.11
  cloud_functions: ^4.3.0
  firebase_remote_config: ^4.2.0
  firebase_analytics: ^10.4.0
  firebase_storage: ^11.2.0
  firebase_messaging: ^14.6.0
  firebase_dynamic_links: ^5.3.0
  firebase_ml_model_downloader: ^0.2.3
  firebase_auth: ^4.6.0
  path_provider: ^2.0.9
  firebase_database: ^10.2.0
  firebase_performance: ^0.9.2
  json_annotation: ^4.4.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.0.0
  twitter_login: ^4.1.0
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.1
  firebase_crashlytics: ^3.3.0
  firebase_auth_platform_interface: ^7.3.0
  http: ^1.2.2
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.8
  cloud_firestore_odm_generator: ^1.0.0-dev.11
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
