// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  /// Per this SO answer by Puf@, it is okay to put this info in GitHub,
  /// as its not really 'secret' https://stackoverflow.com/a/37484053
  ///
  /// Instead of hiding this information, security should be handled
  /// with access rules to individual products.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu2FRBnv0pV01dHHOQuk26pR1oYcZpGTE',
    appId: '1:220375889386:web:bc468dd9e586597b6bae93',
    messagingSenderId: '220375889386',
    projectId: 'flutter-fire-snippets',
    authDomain: 'flutter-fire-snippets.firebaseapp.com',
    storageBucket: 'flutter-fire-snippets.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bbpFcMWgGpKKEmqNw57Al2vdV4QnNP0',
    appId: '1:220375889386:android:1a16e85eeab0d5896bae93',
    messagingSenderId: '220375889386',
    projectId: 'flutter-fire-snippets',
    storageBucket: 'flutter-fire-snippets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNp5_kQjIgyS_UMtv9oRKcbCjOfYB1LNc',
    appId: '1:220375889386:ios:0fec9df2e96f0db36bae93',
    messagingSenderId: '220375889386',
    projectId: 'flutter-fire-snippets',
    storageBucket: 'flutter-fire-snippets.appspot.com',
    iosClientId:
        '220375889386-8v73sv2lia3e7c12h0btp2tfbj0um4it.apps.googleusercontent.com',
    iosBundleId: 'com.fluttersnippets.app',
  );
}
