// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/*
NB: This contains errors!

TODO: ewindmill -- set up env variables and add options back in.

 */

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO: use secrets or demo',
    appId: 'TODO: use secrets or demo',
    messagingSenderId: 'TODO: use secrets or demo',
    projectId: 'TODO: use secrets or demo',
    authDomain: 'TODO: use secrets or demo',
    storageBucket: 'TODO: use secrets or demo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO: use secrets or demo',
    appId: 'TODO: use secrets or demo',
    messagingSenderId: 'TODO: use secrets or demo',
    projectId: 'TODO: use secrets or demo',
    storageBucket: 'TODO: use secrets or demo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO: use secrets or demo',
    appId: 'TODO: use secrets or demo',
    messagingSenderId: 'TODO: use secrets or demo',
    projectId: 'TODO: use secrets or demo',
    storageBucket: 'TODO: use secrets or demo',
    iosClientId:'TODO: use secrets or demo',
    iosBundleId: 'com.fluttersnippets.app',
  );
}
