name: Run CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
    - "packages/**"
    - ".github/workflows"
  push:
    paths-ignore:
    - "**.md"

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - name: "Git Checkout"
      uses: actions/checkout@v2

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: "Install Node"
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - uses: actions/setup-java@v2
      name: "Install Java"
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: "Install Flutter"
      run: |
        sh .github/workflows/scripts/install-flutter.sh stable

    - name: "Install Tools"
      run: |
        sh ./.github/workflows/scripts/install-tools.sh
        flutter config --no-enable-web --no-enable-ios --no-enable-macos-desktop
        sudo npm i -g firebase-tools
#
    - name: "Start Firebase Emulator"
      run: |
        sh ./.github/workflows/scripts/start-firebase-emulator.sh

    - name: "Drive Example"
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        arch: x86_64
        disable-animations: true
        # Firebase Firestore works without Google Play Services, so we don't use the `googleapis`
        # emulator target as it's considerably slower on CI.
        target: default
        profile: Nexus 5X
        script: bash ./.github/workflows/scripts/drive-app.sh firestore_snippets
